variant = "loose"

[[issues]]
file = "shared/code/tce_functions_authorization.php"
code = "function-name"
message = "Function name `F_getAuthorizedUsers` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_authorization.php"
code = "function-name"
message = "Function name `F_isAuthorizedUser` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_authorization.php"
code = "function-name"
message = "Function name `F_syncUserGroups` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_addLogAnswers` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_addQuestionAnswers` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_checkTestStatus` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_createTest` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_executeTest` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_getTestData` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_getUserTests` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_isTestOverLimits` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_isValidTestUser` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_newTestLog` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_printTestInfo` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_questionForm` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_questionsMenu` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_repeatTest` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_selectAnswers` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_terminateUserTest` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_testComment` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_testLoginForm` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_updateQuestionLog` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_updateTestComment` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_updateTestuserStat` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test_stats.php"
code = "function-name"
message = "Function name `F_getAllUsersTestStat` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test_stats.php"
code = "function-name"
message = "Function name `F_getRawTestStat` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test_stats.php"
code = "function-name"
message = "Function name `F_getTestIDs` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test_stats.php"
code = "function-name"
message = "Function name `F_getTestStat` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test_stats.php"
code = "function-name"
message = "Function name `F_getUserTestStat` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test_stats.php"
code = "function-name"
message = "Function name `F_getUserTestTotals` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test_stats.php"
code = "function-name"
message = "Function name `F_normalizeTestStatAverages` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test_stats.php"
code = "function-name"
message = "Function name `F_printTestResultStat` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test_stats.php"
code = "function-name"
message = "Function name `F_printTestStat` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test_stats.php"
code = "function-name"
message = "Function name `F_printUserTestStat` should be in snake case."
count = 1
