variant = "loose"

[[issues]]
file = "shared/code/tce_db_dal_oracle.php"
code = "non-existent-class-like"
message = "Cannot find class, interface, enum, or type alias `Number`."
count = 2

[[issues]]
file = "shared/code/tce_db_dal_oracle.php"
code = "non-existent-class-like"
message = "Cannot find class, interface, enum, or type alias `Oracle`."
count = 1

[[issues]]
file = "shared/code/tce_db_dal_oracle.php"
code = "non-existent-class-like"
message = "Cannot find class, interface, enum, or type alias `Returns`."
count = 2

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "array-to-string-conversion"
message = "Potential array in middle operand of string concatenation."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "impossible-condition"
message = "This condition (type `false`) will always evaluate to false."
count = 5

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "invalid-array-access"
message = "Cannot perform array access on value of type `unknown-ref(Returns)`."
count = 17

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "invalid-array-element-key"
message = "Invalid array key type."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "mixed-array-access"
message = "Unsafe array access on type `mixed`."
count = 4

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "mixed-operand"
message = "Invalid middle operand: type `mixed` cannot be reliably used in string concatenation."
count = 23

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "mixed-operand"
message = "Invalid right operand: type `mixed` cannot be reliably used in string concatenation."
count = 6

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "mixed-operand"
message = "Left operand in `>` comparison has `mixed` type."
count = 2

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "no-value"
message = "Argument #1 passed to function `f_db_fetch_array` has type `never`, meaning it cannot produce a value."
count = 5

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "possibly-null-operand"
message = "Possibly null left operand used in string concatenation (type `non-empty-string|null`)."
count = 2

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "possibly-null-operand"
message = "Possibly null middle operand used in string concatenation (type `non-empty-string|null`)."
count = 3

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "possibly-undefined-int-array-index"
message = "Possibly undefined array index accessed on `list<string>`."
count = 8

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "possibly-undefined-int-array-index"
message = "Possibly undefined array key `int` accessed on `array<int, non-empty-string>`."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "possibly-undefined-string-array-index"
message = "Possibly undefined array key `string('session_user_id')` accessed on `array<non-empty-string, mixed>`."
count = 2

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "possibly-undefined-string-array-index"
message = "Possibly undefined array key `string('test_mcma_radio')` accessed on `array<array-key, mixed>`."
count = 2

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "possibly-undefined-string-array-index"
message = "Possibly undefined array key `string('test_noanswer_enabled')` accessed on `array<array-key, mixed>`."
count = 2

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "possibly-undefined-string-array-index"
message = "Possibly undefined array key `truthy-string` accessed on `array<truthy-string, non-empty-string>`."
count = 4

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "redundant-condition"
message = "This condition (type `true`) will always evaluate to true."
count = 2
