variant = "loose"

[[issues]]
file = "test/integration/AdminControllerHttpTest.php"
code = "mixed-array-access"
message = "Unsafe array access on type `mixed`."
count = 2

[[issues]]
file = "test/integration/AdminControllerHttpTest.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 1

[[issues]]
file = "test/integration/AdminControllerHttpTest.php"
code = "possibly-null-argument"
message = "Argument #2 of function `explode` is possibly `null`, but parameter type `string` does not accept it."
count = 1

[[issues]]
file = "test/integration/AdminControllerHttpTest.php"
code = "possibly-null-array-access"
message = "Cannot perform array access on possibly `null` value."
count = 2

[[issues]]
file = "test/integration/AdminControllerHttpTest.php"
code = "possibly-null-operand"
message = "Possibly null middle operand used in string concatenation (type `int|null`)."
count = 4

[[issues]]
file = "test/integration/AdminControllerHttpTest.php"
code = "possibly-null-operand"
message = "Possibly null right operand used in string concatenation (type `int|null`)."
count = 4

[[issues]]
file = "test/integration/AdminControllerHttpTest.php"
code = "possibly-undefined-int-array-index"
message = "Possibly undefined array key 3 accessed on `array{1?: int, 2?: int, 3?: int, 4?: int, 5?: int}`."
count = 1

[[issues]]
file = "test/integration/AdminControllerHttpTest.php"
code = "possibly-undefined-int-array-index"
message = "Possibly undefined array key `int(0)` accessed on `array<int, string>`."
count = 1

[[issues]]
file = "test/integration/AdminControllerHttpTest.php"
code = "possibly-undefined-int-array-index"
message = "Possibly undefined array key `int(1)` accessed on `array<array-key, string>`."
count = 3

[[issues]]
file = "test/integration/AdminControllerHttpTest.php"
code = "possibly-undefined-int-array-index"
message = "Possibly undefined array key `int(1)` accessed on `array<int, array<int, string>>`."
count = 1

[[issues]]
file = "test/integration/AdminControllerHttpTest.php"
code = "possibly-undefined-int-array-index"
message = "Possibly undefined array key `int(1)|int(2)` accessed on `array{1: int, 2: int}`."
count = 1

[[issues]]
file = "test/integration/AdminControllerHttpTest.php"
code = "possibly-undefined-int-array-index"
message = "Possibly undefined array key `int(1)|int(2)|int(3)|int(4)|int(5)` accessed on `array{1: string('Persist single choice'), 2: string('Persist multiple choice<!--TMF_CHECKBOX-->'), 3: string('Persist text'), 4: string('Persist ordering'), 5: string('Persist matching<!--TMF_MATCH_POSITIONS:2-->')}`."
count = 1

[[issues]]
file = "test/integration/AdminControllerHttpTest.php"
code = "possibly-undefined-int-array-index"
message = "Possibly undefined array key `int(1)|int(2)|int(3)|int(4)|int(5)` accessed on `array{1?: int, 2?: int, 3?: int, 4?: int, 5?: int}`."
count = 2

[[issues]]
file = "test/integration/AdminControllerHttpTest.php"
code = "possibly-undefined-int-array-index"
message = "Possibly undefined array key `int(1)|int(2)|int(4)|int(5)` accessed on `array{1?: array{1: int, 2: int}, 2?: array{1: int, 2: int}, 4?: array{1: int, 2: int}, 5?: array{1: int, 2: int}}`."
count = 1

[[issues]]
file = "test/integration/AdminControllerHttpTest.php"
code = "possibly-undefined-int-array-index"
message = "Possibly undefined array key `int(5)` accessed on `array<int, string>`."
count = 1

[[issues]]
file = "test/integration/AdminControllerHttpTest.php"
code = "possibly-undefined-int-array-index"
message = "Possibly undefined array key `int(8)` accessed on `array<int, string>`."
count = 1

[[issues]]
file = "test/integration/AdminControllerHttpTest.php"
code = "reference-to-undefined-variable"
message = "Reference created from a previously undefined variable `$versionMatch`."
count = 1
