variant = "loose"

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_addQuestionAnswers` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_checkTestStatus` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_createTest` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_executeTest` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_getUserTests` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_newTestLog` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_printTestInfo` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_questionForm` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_questionsMenu` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_repeatTest` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_selectAnswers` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_testLoginForm` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test.php"
code = "function-name"
message = "Function name `F_updateQuestionLog` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test_stats.php"
code = "function-name"
message = "Function name `F_getAllUsersTestStat` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test_stats.php"
code = "function-name"
message = "Function name `F_getRawTestStat` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test_stats.php"
code = "function-name"
message = "Function name `F_printTestResultStat` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test_stats.php"
code = "function-name"
message = "Function name `F_printTestStat` should be in snake case."
count = 1

[[issues]]
file = "shared/code/tce_functions_test_stats.php"
code = "function-name"
message = "Function name `F_printUserTestStat` should be in snake case."
count = 1
